# coding:utf8

if __name__ == '__main__':
    parent_path = """C:/Users/javac/AppData/Local/JianyingPro/User Data/Projects/com.lveditor.draft/202111031059"""
    fw = open(parent_path + """/draft_content.json-w""", "w", encoding="UTF-8")
    st = str(open(parent_path + """/draft_content.json.bak""", "r", encoding="UTF-8").readlines())
    st = st.replace("哈都不", "Hadoop")
    st = st.replace("哈杜普", "Hadoop")
    st = st.replace("他", "它")
    st = st.replace("楼口", "Local")
    st = st.replace("logo", "Local")
    st = st.replace("loco", "Local")
    st = st.replace("林尼克", "Linux")
    st = st.replace("李纽克斯", "Linux")
    st = st.replace(" spa 和", "Spark")
    st = st.replace("18个", "Spark")
    st = st.replace("十八个", "Spark")
    st = st.replace(" spa ", "Spark")
    st = st.replace("spa 可", "Spark")
    st = st.replace("史帕克", "Spark")
    st = st.replace("界 vm", "JVM")
    st = st.replace("jmm", "JVM")
    st = st.replace("接 vm", "JVM")
    st = st.replace("踏实课", "Task")
    st = st.replace("踏实克", "Task")
    st = st.replace("接离开", "JDK")
    st = st.replace("渗透", "Cent")
    st = st.replace("寻机", "虚拟机")
    st = st.replace("vivo vr", "VMWare")
    st = st.replace("星", "*")
    st = st.replace("gram", "JVM")
    st = st.replace("进城", "进程")
    st = st.replace("晋城", "进程")
    st = st.replace("县城", "线程")
    st = st.replace("现成", "线程")
    st = st.replace("鸡群", "集群")
    st = st.replace("机群", "集群")
    st = st.replace("肌群", "集群")
    st = st.replace("接龙性", "兼容性")
    st = st.replace("威尔worker斯带森", "VMWare WorkStation")
    st = st.replace("沃克", "Worker")
    st = st.replace("蜗壳", "Worker")
    st = st.replace("窝可", "Worker")
    st = st.replace("窝克", "Worker")
    st = st.replace("无可", "Worker")
    st = st.replace("马斯特", "Master")
    st = st.replace("砖窝", "Driver")
    st = st.replace("主要我", "Driver")
    st = st.replace("砖瓦", "Driver")
    st = st.replace("专我", "Driver")
    st = st.replace("drawer", "Driver")
    st = st.replace("dread 我", "Driver")
    st = st.replace("追我", "Driver")
    st = st.replace("一个q特", "Executor")
    st = st.replace("一个 q 特", "Executor")
    st = st.replace("艾克的 q 特", "Executor")
    st = st.replace("ascot", "Executor")
    st = st.replace("equip", "Executor")
    st = st.replace("Lakota", "Executor")
    st = st.replace("lakota", "Executor")
    st = st.replace("一个客客", "Executor")
    st = st.replace("一个扣特", "Executor")
    st = st.replace("ipa", "API")
    st = st.replace("记硕", "计数")

    fw.write(st)
    fw.flush()
    fw.close()
